# PREGUNTA 1

In [2]:
import pandas as pd
from pathlib import Path
import gzip

In [3]:
# -----------------------------------
# Cargar las rutas de manera relativa
# -----------------------------------
DATA_DIR = Path('../data')
DATA_FILE = DATA_DIR / 'data.csv.gz'

# ---------------------------------
# Validar la existencia del archivo
# ---------------------------------
assert DATA_FILE.exists()

In [4]:
# ---------------------------------
# Identificar los separadores
# ---------------------------------
with gzip.open(DATA_FILE, "rt", encoding="utf-8") as f:
    lineas = f.read().splitlines()

print(repr(lineas[0]))
print(repr(lineas[1]))

'E\t1\t1999-02-28\tb,g,f\tjjj:12,bbb:3,ddd:9,ggg:8,hhh:2'
'A\t2\t1999-10-28\ta,f,c\tccc:2,ddd:0,aaa:3,hhh:9'

In [5]:
# ---------------------------------
# Leer los datos
# ---------------------------------
data = pd.read_csv(DATA_FILE, sep="\t", header=None)
data

    0  1           2        3                                     4
0   E  1  1999-02-28    b,g,f        jjj:12,bbb:3,ddd:9,ggg:8,hhh:2
1   A  2  1999-10-28    a,f,c               ccc:2,ddd:0,aaa:3,hhh:9
2   B  5  1998-05-02  f,e,a,c              ddd:2,ggg:5,ccc:6,jjj:12
3   A  3  1999-08-28      a,b               hhh:9,iii:5,eee:7,bbb:1
4   C  6  1999-12-01  f,g,d,a              iii:6,ddd:5,eee:4,jjj:12
5   A  7  1998-07-28      c,d         bbb:2,hhh:0,ccc:4,fff:1,aaa:7
6   A  9  1997-02-28    g,d,a   aaa:5,fff:8,ddd:2,iii:0,jjj:7,ccc:1
7   B  1  1999-05-10      b,a                     fff:3,hhh:1,ddd:2
8   E  2  1997-04-12  d,e,a,f   eee:4,ccc:5,iii:9,fff:7,ggg:6,bbb:2
9   B  3  1999-11-23  d,b,g,f   bbb:7,jjj:9,fff:5,iii:4,ggg:3,eee:3
10  C  7  1998-01-17  d,c,f,b        hhh:6,eee:4,iii:0,fff:2,jjj:12
11  C  5  1998-12-28  d,e,a,c                     bbb:7,iii:6,ggg:9
12  D  3  1999-10-15  g,e,f,b         bbb:9,aaa:3,ccc:6,fff:4,eee:2
13  E  8  1998-11-01      c,f                    aaa:8,ddd:5,jjj:12
14  B  9  1999-08-12      d,b         ccc:7,jjj:6,fff:7,ddd:3,aaa:2
15  D  8  1997-12-01      f,e               ccc:8,eee:6,bbb:9,ddd:3
16  E  3  1997-07-28    e,b,f   bbb:6,iii:3,hhh:5,fff:4,ggg:9,ddd:2
17  D  5  1998-08-12      g,a                     hhh:4,jjj:5,ccc:9
18  E  8  1999-08-24  e,c,f,a                     ccc:1,iii:6,fff:9
19  E  9  1998-01-23      e,a                     bbb:9,aaa:3,fff:1
20  E  7  1999-06-22      e,f                     ddd:9,iii:2,aaa:4
21  E  3  1999-04-24    c,b,g                     ccc:5,fff:8,iii:7
22  D  5  1999-06-25    c,f,a                    eee:3,jjj:17,ddd:7
23  A  9  1999-08-25    f,a,d        jjj:12,ggg:7,ccc:7,ddd:9,bbb:3
24  E  4  1997-07-26      c,d   jjj:6,ccc:4,aaa:1,hhh:9,iii:7,ggg:8
25  E  6  1997-09-24    e,d,c   fff:3,eee:6,iii:4,bbb:7,ddd:4,ccc:1
26  A  8  1997-09-28    a,e,f                     fff:0,ddd:5,ccc:4
27  E  5  1999-06-22    c,a,g        ggg:6,hhh:3,ddd:9,ccc:10,jjj:7
28  A  6  1999-07-29      f,e        hhh:6,jjj:13,eee:5,iii:7,ccc:3
29  C  0  1999-08-22  f,c,a,g  eee:1,fff:4,aaa:2,ccc:7,ggg:10,ddd:6
30  A  9  1998-04-26      b,f         ccc:6,aaa:9,eee:5,ddd:0,bbb:3
31  D  3  1998-02-24      b,f   bbb:7,hhh:1,aaa:6,iii:4,fff:9,ddd:5
32  E  5  1999-03-24      a,c               fff:3,ccc:1,ggg:3,eee:5
33  B  4  1998-03-23    b,f,c   iii:7,ggg:3,ddd:0,jjj:8,hhh:5,ccc:1
34  B  6  1999-04-21    f,a,e         hhh:6,ccc:3,jjj:9,bbb:8,ddd:7
35  D  7  1999-02-29      a,f                     aaa:1,fff:5,ddd:3
36  B  8  1997-05-21      c,a       ddd:5,jjj:17,iii:7,ccc:10,bbb:4
37  C  9  1997-07-22  c,a,e,f                     eee:3,fff:2,hhh:6
38  E  1  1999-09-28      e,d                     fff:9,iii:2,eee:5
39  E  5  1998-01-26    f,a,d                     hhh:8,ggg:3,jjj:5

In [6]:
# -----------------------------------
# Suma Columna 1
# -----------------------------------
suma_columna1 = data[1].sum()
suma_columna1

214

# PREGUNTA 2

In [7]:
conteo_letras = {}

for letra in data[0]:
    if letra in conteo_letras:
        conteo_letras[letra] += 1
    else:
        conteo_letras[letra] = 1
        print(conteo_letras)


print(letra, conteo_letras)

resultado = sorted(conteo_letras.items())
print(resultado)

{'E': 1}
{'E': 1, 'A': 1}
{'E': 1, 'A': 1, 'B': 1}
{'E': 1, 'A': 2, 'B': 1, 'C': 1}
{'E': 2, 'A': 4, 'B': 3, 'C': 3, 'D': 1}
E {'E': 14, 'A': 8, 'B': 7, 'C': 5, 'D': 6}
[('A', 8), ('B', 7), ('C', 5), ('D', 6), ('E', 14)]

# PREGUNTA 3

In [8]:
dic_conteo = {}

for letra in data[0]:
    if letra not in dic_conteo:
        dic_conteo[letra] = data.loc[data[0] == letra, 1].sum()

resultado = sorted(dic_conteo.items())
print(resultado)

[('A', 53), ('B', 36), ('C', 27), ('D', 31), ('E', 67)]

# PREGUNTA 4

In [9]:
data = pd.read_csv(DATA_FILE, sep="\t", header=None)

data[2] = data[2].astype(str)
data["mes"] = data[2].str[5:7]
data["año"] = data[2].str[0:4]
data["dia"] = data[2].str[8:10]

In [10]:
dict_mes = {}

for element in data["mes"]:
    if element in dict_mes:
        dict_mes[element] += 1
    else:
        dict_mes[element] = 1

resultado = sorted(dict_mes.items())
print(resultado)

[('01', 3), ('02', 4), ('03', 2), ('04', 4), ('05', 3), ('06', 3), ('07', 5), ('08', 6), ('09', 3), ('10', 2), ('11', 2), ('12', 3)]

# PREGUNTA 5

In [11]:
dict_max_min = {}

for letter in data[0]: 
   dict_max_min[letter] = (letter,
                           data.loc[data[0] == letter, 1].max(), 
                           data.loc[data[0] == letter, 1].min()
                           )


resultado = sorted(dict_max_min.values())
print(resultado)

[('A', 9, 2), ('B', 9, 1), ('C', 9, 0), ('D', 8, 3), ('E', 9, 1)]

# PREGUNTA 6

In [12]:
# ----------------------------------------------------------------------------------
# Se crea metrics independeintes separando cada par "aaa: 1" usando , como separador
# ----------------------------------------------------------------------------------
data["metrics_independientes"] = data[4].str.split(",")
data

,0,1,2,3,4,mes,año,dia,metrics_independientes
0,E,1,1999-02-28,"b,g,f","jjj:12,bbb:3,ddd:9,ggg:8,hhh:2",02,1999,28,"[jjj:12, bbb:3, ddd:9, ggg:8, hhh:2]"
1,A,2,1999-10-28,"a,f,c","ccc:2,ddd:0,aaa:3,hhh:9",10,1999,28,"[ccc:2, ddd:0, aaa:3, hhh:9]"
2,B,5,1998-05-02,"f,e,a,c","ddd:2,ggg:5,ccc:6,jjj:12",05,1998,02,"[ddd:2, ggg:5, ccc:6, jjj:12]"
3,A,3,1999-08-28,"a,b","hhh:9,iii:5,eee:7,bbb:1",08,1999,28,"[hhh:9, iii:5, eee:7, bbb:1]"
4,C,6,1999-12-01,"f,g,d,a","iii:6,ddd:5,eee:4,jjj:12",12,1999,01,"[iii:6, ddd:5, eee:4, jjj:12]"
5,A,7,1998-07-28,"c,d","bbb:2,hhh:0,ccc:4,fff:1,aaa:7",07,1998,28,"[bbb:2, hhh:0, ccc:4, fff:1, aaa:7]"
6,A,9,1997-02-28,"g,d,a","aaa:5,fff:8,ddd:2,iii:0,jjj:7,ccc:1",02,1997,28,"[aaa:5, fff:8, ddd:2, iii:0, jjj:7, ccc:1]"
7,B,1,1999-05-10,"b,a","fff:3,hhh:1,ddd:2",05,1999,10,"[fff:3, hhh:1, ddd:2]"
8,E,2,1997-04-12,"d,e,a,f","eee:4,ccc:5,iii:9,fff:7,ggg:6,bbb:2",04,1997,12,"[eee:4, ccc:5, iii:9, fff:7, ggg:6, bbb:2]"
9,B,3,1999-11-23,"d,b,g,f","bbb:7,jjj:9,fff:5,iii:4,ggg:3,eee:3",11,1999,23,"[bbb:7, jjj:9, fff:5, iii:4, ggg:3, eee:3]"
10,C,7,1998-01-17,"d,c,f,b","hhh:6,eee:4,iii:0,fff:2,jjj:12",01,1998,17,"[hhh:6, eee:4, iii:0, fff:2, jjj:12]"
11,C,5,1998-12-28,"d,e,a,c","bbb:7,iii:6,ggg:9",12,1998,28,"[bbb:7, iii:6, ggg:9]"
12,D,3,1999-10-15,"g,e,f,b","bbb:9,aaa:3,ccc:6,fff:4,eee:2",10,1999,15,"[bbb:9, aaa:3, ccc:6, fff:4, eee:2]"
13,E,8,1998-11-01,"c,f","aaa:8,ddd:5,jjj:12",11,1998,01,"[aaa:8, ddd:5, jjj:12]"
14,B,9,1999-08-12,"d,b","ccc:7,jjj:6,fff:7,ddd:3,aaa:2",08,1999,12,"[ccc:7, jjj:6, fff:7, ddd:3, aaa:2]"
15,D,8,1997-12-01,"f,e","ccc:8,eee:6,bbb:9,ddd:3",12,1997,01,"[ccc:8, eee:6, bbb:9, ddd:3]"
16,E,3,1997-07-28,"e,b,f","bbb:6,iii:3,hhh:5,fff:4,ggg:9,ddd:2",07,1997,28,"[bbb:6, iii:3, hhh:5, fff:4, ggg:9, ddd:2]"
17,D,5,1998-08-12,"g,a","hhh:4,jjj:5,ccc:9",08,1998,12,"[hhh:4, jjj:5, ccc:9]"
18,E,8,1999-08-24,"e,c,f,a","ccc:1,iii:6,fff:9",08,1999,24,"[ccc:1, iii:6, fff:9]"
19,E,9,1998-01-23,"e,a","bbb:9,aaa:3,fff:1",01,1998,23,"[bbb:9, aaa:3, fff:1]"
20,E,7,1999-06-22,"e,f","ddd:9,iii:2,aaa:4",06,1999,22,"[ddd:9, iii:2, aaa:4]"
21,E,3,1999-04-24,"c,b,g","ccc:5,fff:8,iii:7",04,1999,24,"[ccc:5, fff:8, iii:7]"
22,D,5,1999-06-25,"c,f,a","eee:3,jjj:17,ddd:7",06,1999,25,"[eee:3, jjj:17, ddd:7]"
23,A,9,1999-08-25,"f,a,d","jjj:12,ggg:7,ccc:7,ddd:9,bbb:3",08,1999,25,"[jjj:12, ggg:7, ccc:7, ddd:9, bbb:3]"
24,E,4,1997-07-26,"c,d","jjj:6,ccc:4,aaa:1,hhh:9,iii:7,ggg:8",07,1997,26,"[jjj:6, ccc:4, aaa:1, hhh:9, iii:7, ggg:8]"
25,E,6,1997-09-24,"e,d,c","fff:3,eee:6,iii:4,bbb:7,ddd:4,ccc:1",09,1997,24,"[fff:3, eee:6, iii:4, bbb:7, ddd:4, ccc:1]"
26,A,8,1997-09-28,"a,e,f","fff:0,ddd:5,ccc:4",09,1997,28,"[fff:0, ddd:5, ccc:4]"
27,E,5,1999-06-22,"c,a,g","ggg:6,hhh:3,ddd:9,ccc:10,jjj:7",06,1999,22,"[ggg:6, hhh:3, ddd:9, ccc:10, jjj:7]"
28,A,6,1999-07-29,"f,e","hhh:6,jjj:13,eee:5,iii:7,ccc:3",07,1999,29,"[hhh:6, jjj:13, eee:5, iii:7, ccc:3]"
29,C,0,1999-08-22,"f,c,a,g","eee:1,fff:4,aaa:2,ccc:7,ggg:10,ddd:6",08,1999,22,"[eee:1, fff:4, aaa:2, ccc:7, ggg:10, ddd:6]"
30,A,9,1998-04-26,"b,f","ccc:6,aaa:9,eee:5,ddd:0,bbb:3",04,1998,26,"[ccc:6, aaa:9, eee:5, ddd:0, bbb:3]"
31,D,3,1998-02-24,"b,f","bbb:7,hhh:1,aaa:6,iii:4,fff:9,ddd:5",02,1998,24,"[bbb:7, hhh:1, aaa:6, iii:4, fff:9, ddd:5]"
32,E,5,1999-03-24,"a,c","fff:3,ccc:1,ggg:3,eee:5",03,1999,24,"[fff:3, ccc:1, ggg:3, eee:5]"
33,B,4,1998-03-23,"b,f,c","iii:7,ggg:3,ddd:0,jjj:8,hhh:5,ccc:1",03,1998,23,"[iii:7, ggg:3, ddd:0, jjj:8, hhh:5, ccc:1]"
34,B,6,1999-04-21,"f,a,e","hhh:6,ccc:3,jjj:9,bbb:8,ddd:7",04,1999,21,"[hhh:6, ccc:3, jjj:9, bbb:8, ddd:7]"
35,D,7,1999-02-29,"a,f","aaa:1,fff:5,ddd:3",02,1999,29,"[aaa:1, fff:5, ddd:3]"
36,B,8,1997-05-21,"c,a","ddd:5,jjj:17,iii:7,ccc:10,bbb:4",05,1997,21,"[ddd:5, jjj:17, iii:7, ccc:10, bbb:4]"
37,C,9,1997-07-22,"c,a,e,f","eee:3,fff:2,hhh:6",07,1997,22,"[eee:3, fff:2, hhh:6]"
38,E,1,1999-09-28,"e,d","fff:9,iii:2,eee:5",09,1999,28,"[fff:9, iii:2, eee:5]"
39,E,5,1998-01-26,"f,a,d","hhh:8,ggg:3,jjj:5",01,1998,26,"[hhh:8, ggg:3, jjj:5]"

In [13]:
# --------------------------------------------------------------
# Se separa la información a procesar en columnas independientes
# --------------------------------------------------------------
data_ampliada = data.explode("metrics_independientes")
data_ampliada["metrics_independientes_2"] = data_ampliada["metrics_independientes"].str.split(":")

data_ampliada["metrics_elemento_0"] = data_ampliada["metrics_independientes_2"].str[0]
data_ampliada["metrics_elemento_1"] = data_ampliada["metrics_independientes_2"].str[1]
data_ampliada["metrics_elemento_1"] = data_ampliada["metrics_elemento_1"].astype(int)
data_ampliada

,0,1,2,3,4,mes,año,dia,metrics_independientes,metrics_independientes_2,metrics_elemento_0,metrics_elemento_1
0,E,1,1999-02-28,"b,g,f","jjj:12,bbb:3,ddd:9,ggg:8,hhh:2",02,1999,28,jjj:12,"[jjj, 12]",jjj,12
0,E,1,1999-02-28,"b,g,f","jjj:12,bbb:3,ddd:9,ggg:8,hhh:2",02,1999,28,bbb:3,"[bbb, 3]",bbb,3
0,E,1,1999-02-28,"b,g,f","jjj:12,bbb:3,ddd:9,ggg:8,hhh:2",02,1999,28,ddd:9,"[ddd, 9]",ddd,9
0,E,1,1999-02-28,"b,g,f","jjj:12,bbb:3,ddd:9,ggg:8,hhh:2",02,1999,28,ggg:8,"[ggg, 8]",ggg,8
0,E,1,1999-02-28,"b,g,f","jjj:12,bbb:3,ddd:9,ggg:8,hhh:2",02,1999,28,hhh:2,"[hhh, 2]",hhh,2
...,...,...,...,...,...,...,...,...,...,...,...,...
38,E,1,1999-09-28,"e,d","fff:9,iii:2,eee:5",09,1999,28,iii:2,"[iii, 2]",iii,2
38,E,1,1999-09-28,"e,d","fff:9,iii:2,eee:5",09,1999,28,eee:5,"[eee, 5]",eee,5
39,E,5,1998-01-26,"f,a,d","hhh:8,ggg:3,jjj:5",01,1998,26,hhh:8,"[hhh, 8]",hhh,8
39,E,5,1998-01-26,"f,a,d","hhh:8,ggg:3,jjj:5",01,1998,26,ggg:3,"[ggg, 3]",ggg,3
39,E,5,1998-01-26,"f,a,d","hhh:8,ggg:3,jjj:5",01,1998,26,jjj:5,"[jjj, 5]",jjj,5

In [14]:
# Agrupamos por la métrica, calculamos min y max, y ordenamos el resultado final
resultado = list(map(tuple,
                    data_ampliada.
                    groupby("metrics_elemento_0")["metrics_elemento_1"].
                    agg(["min", "max"]).
                    reset_index().values
                    )
                )

print(resultado)

[('aaa', 1, 9), ('bbb', 1, 9), ('ccc', 1, 10), ('ddd', 0, 9), ('eee', 1, 7), ('fff', 0, 9), ('ggg', 3, 10), ('hhh', 0, 9), ('iii', 0, 9), ('jjj', 5, 17)]

# PREGUNTA 7

In [15]:
lista_numero_conteo = {}

for numero in data[1]: 
    if numero not in lista_numero_conteo:
        lista_numero_conteo[numero] = data.loc[data[1] == numero, 0].tolist()
     
resultado = sorted(lista_numero_conteo.items())
resultado

[(0, ['C']),
 (1, ['E', 'B', 'E']),
 (2, ['A', 'E']),
 (3, ['A', 'B', 'D', 'E', 'E', 'D']),
 (4, ['E', 'B']),
 (5, ['B', 'C', 'D', 'D', 'E', 'E', 'E']),
 (6, ['C', 'E', 'A', 'B']),
 (7, ['A', 'C', 'E', 'D']),
 (8, ['E', 'D', 'E', 'A', 'B']),
 (9, ['A', 'B', 'E', 'A', 'A', 'C'])]

# PREGUNTA 8

In [16]:
resultado = list(data.groupby(1)[0].   # Se agrupa tomando a la columna data[]
                 agg(lambda s: sorted(s.unique())).
                 items())
resultado

[(0, ['C']),
 (1, ['B', 'E']),
 (2, ['A', 'E']),
 (3, ['A', 'B', 'D', 'E']),
 (4, ['B', 'E']),
 (5, ['B', 'C', 'D', 'E']),
 (6, ['A', 'B', 'C', 'E']),
 (7, ['A', 'C', 'D', 'E']),
 (8, ['A', 'B', 'D', 'E']),
 (9, ['A', 'B', 'C', 'E'])]

# PREGUNTA 9

In [48]:
conteo_metrics = {}

for element in data_ampliada["metrics_elemento_0"]:
    if element not in conteo_metrics:
        conteo_metrics[element] = 1
    else:
        conteo_metrics[element] += 1

resultado = dict(sorted(conteo_metrics.items()))
resultado

{'aaa': 13,
 'bbb': 16,
 'ccc': 23,
 'ddd': 23,
 'eee': 15,
 'fff': 20,
 'ggg': 13,
 'hhh': 16,
 'iii': 18,
 'jjj': 18}

# PREGUNTA 10

In [ ]:
n_codes   = data[3].str.split(",").str.len() # Se crea una columa conformada por la longitud de las listas resultantes de separar data[3] por ,
n_metrics = data[4].str.split(",").str.len()

resultado = list(zip(data[0].tolist(), n_codes.tolist(), n_metrics.tolist()))   # Se usa zip apra agrupar las tres columnas: data[0], n_codes y n_metrics
print(resultado)

0     3
1     3
2     4
3     2
4     4
5     2
6     3
7     2
8     4
9     4
10    4
11    4
12    4
13    2
14    2
15    2
16    3
17    2
18    4
19    2
20    2
21    3
22    3
23    3
24    2
25    3
26    3
27    3
28    2
29    4
30    2
31    2
32    2
33    3
34    3
35    2
36    2
37    4
38    2
39    3
Name: 3, dtype: int64

# PREGUNTA 11

In [ ]:
suma = (data.assign(letra = data[3].str.split(","))   # con data.assign se crea una copia de data que contiene una columna llamada letra, en donde los elmentos de data[3] son elementos de una lista
        .explode("letra")     # Generan nuevas filas en las que cada elemento de data[3] esta individualmente conservando la información de las demás
        .groupby("letra")[1]  # Se usa a letra como llave y a data[1] como valor
        .sum()
)

resultado = suma.to_dict()
resultado

{'a': 122, 'b': 49, 'c': 91, 'd': 73, 'e': 86, 'f': 134, 'g': 35}

# PREGUNTA 12

In [ ]:
resultado = (
    data.assign(llave_numero=data[4].str.split(","))   # Se usa assig para crear una copia de data en la cual se inserta una nueva columna (llave_numero). Esta columna es una lista que contiene los elementos resultantes de separar metrics por ,
        .explode("llave_numero")                       # Se usa explode para que cada elemento de llave_numero tenga so propia fila, respetando la información de las demás columnas 
        .assign(valor=lambda d: d["llave_numero"].str.split(":").str[1].astype(int))   # Se usa assign para crear una nueva columna llamada valor conformada por la parte numérica de llave_numero
        .groupby(0)["valor"]                           # groupby: se usa a data[0] como llave y data["valor"] como valor
        .sum()
        .to_dict()
)

resultado

{'A': 177, 'B': 187, 'C': 114, 'D': 136, 'E': 324}